### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by whilei** [rotblauer/mbtileserver#1]
```
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 systemd[1]: mbtileserver.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 systemd[1]: mbtileserver.service: Failed with result 'exit-code'.
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 systemd[1]: mbtileserver.service: Scheduled restart job, restart counter is at 5.
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 systemd[1]: Stopped mbtileserver.service - mbtileserver.
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 systemd[1]: Started mbtileserver.service - mbtileserver.
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: time="2024-12-10T00:58:51Z" level=info msg="Searching for tilesets in /mnt/cattracks_volume/tdata/tilesets\n"
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8532f7]
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: goroutine 1 [running]:
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: crawshaw.io/sqlite.(*Stmt).Finalize(0x0)
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /root/go/pkg/mod/crawshaw.io/sqlite@v0.3.3-0.20220618202545-d1964889ea3c/sqlite.go:556 +0x17
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: github.com/brendan-ward/mbtiles-go.validateRequiredTables(0xc00023ec00?)
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /root/go/pkg/mod/github.com/brendan-ward/mbtiles-go@v0.1.1-0.20230310232339-6c48cea51706/mbtiles.go:277 +0x143
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: github.com/brendan-ward/mbtiles-go.Open({0xc00023ec00, 0x38})
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /root/go/pkg/mod/github.com/brendan-ward/mbtiles-go@v0.1.1-0.20230310232339-6c48cea51706/mbtiles.go:77 +0x270
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: github.com/consbio/mbtileserver/handlers.newTileset(0xc00022d220, {0xc00023ec00, 0x38}, {0xc00023ec25, 0xb}, {0xc000426210, 0x15})
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /usr/local/src/mbtileserver/handlers/tileset.go:34 +0x65
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: github.com/consbio/mbtileserver/handlers.(*ServiceSet).AddTileset(0xc00022d220, {0xc00023ec00, 0x38}, {0xc00023ec25, 0xb})
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /usr/local/src/mbtileserver/handlers/serviceset.go:73 +0xa6
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: main.serve()
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /usr/local/src/mbtileserver/main.go:327 +0x2358
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: main.glob..func1(0xc0000e2700?, {0xa51c49?, 0x4?, 0xa51c4d?})
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /usr/local/src/mbtileserver/main.go:57 +0xb8
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: github.com/spf13/cobra.(*Command).execute(0xf4f220, {0xc0000b2010, 0x6, 0x6})
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: github.com/spf13/cobra.(*Command).ExecuteC(0xf4f220)
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: github.com/spf13/cobra.(*Command).Execute(...)
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]: main.main()
Dec 10 00:58:51 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[663932]:         /usr/local/src/mbtileserver/main.go:214 +0x1a

```

**Comment by whilei** [comment]
tiles exist

```
root@cattracks-debian-s-2vcpu-2gb-sfo3-01:~# ls -lshart /mnt/cattracks_volume/tdata/tilesets
total 8.1G
4.0G -rw-r--r-- 1 root root 4.0G Dec 18  2023 master.mbtiles
1.8M -rw-r--r-- 1 root root 1.8M Dec 18  2023 places.mbtiles
102M -rw-r--r-- 1 root root 102M Dec 20  2023 Chishiki.level-23.mbtiles
 68K -rw-r--r-- 1 root root  68K Dec 20  2023 QP1A.191005.007.A3_Pixel_XL.level-23.mbtiles
 72K -rw-r--r-- 1 root root  72K Dec 20  2023 _.level-23.mbtiles
438M -rw-r--r-- 1 root root 438M Dec 20  2023 iPhone.level-23.mbtiles
1.3M -rw-r--r-- 1 root root 1.3M Dec 20  2023 iPhone_8.level-23.mbtiles
 50M -rw-r--r-- 1 root root  50M Dec 20  2023 jlc.level-23.mbtiles
156M -rw-r--r-- 1 root root 156M Dec 20  2023 jr.level-23.mbtiles
9.4M -rw-r--r-- 1 root root 9.4M Dec 20  2023 kd.level-23.mbtiles
 78M -rw-r--r-- 1 root root  77M Dec 20  2023 kk.level-23.mbtiles
 83M -rw-r--r-- 1 root root  83M Dec 20  2023 mat.level-23.mbtiles
472K -rw-r--r-- 1 root root 472K Dec 20  2023 pancho.level-23.mbtiles
 83M -rw-r--r-- 1 root root  83M Dec 20  2023 pr.level-23.mbtiles
300K -rw-r--r-- 1 root root 300K Dec 20  2023 ric.level-23.mbtiles
220M -rw-r--r-- 1 root root 220M Dec 20  2023 rj.level-23.mbtiles
 40K -rw-r--r-- 1 root root  40K Dec 20  2023 tester.level-23.mbtiles
2.0M -rw-r--r-- 1 root root 2.0M Jul 29 05:44 ia_ELEMNT_ROAM.level-23.mbtiles
 18M -rw-r--r-- 1 root root  18M Dec  9 23:01 devop.mbtiles
1.3G -rw-r--r-- 1 root root 1.3G Dec 10 00:58 rye.level-23.mbtiles
1.7G -rw-r--r-- 1 root root 1.7G Dec 10 00:58 ia.level-23.mbtiles
 32K -rw-r--r-- 1 root root  32K Dec 10 00:58 iPhone_16_Pro.level-23.mbtiles
 32K -rw-r--r-- 1 root root  32K Dec 10 00:58 genpop.level-23.mbtiles
932K -rw-r--r-- 1 root root 932K Dec 10 18:38 edge.mbtiles
 12K drwxr-xr-x 6 root root  12K Dec 10 18:38 ..
4.0K drwxr-xr-x 2 root root 4.0K Dec 10 18:38 .
```

**Comment by whilei** [comment]
restart fixed

```
root@cattracks-debian-s-2vcpu-2gb-sfo3-01:~# systemctl restart mbtileserver.service 
root@cattracks-debian-s-2vcpu-2gb-sfo3-01:~# systemctl status mbtileserver.service
● mbtileserver.service - mbtileserver
     Loaded: loaded (/etc/systemd/system/mbtileserver.service; enabled; preset: enabled)
     Active: active (running) since Tue 2024-12-10 18:43:33 UTC; 5s ago
   Main PID: 701806 (mbtileserver)
      Tasks: 5 (limit: 2314)
     Memory: 29.8M
        CPU: 103ms
     CGroup: /system.slice/mbtileserver.service
             └─701806 /usr/local/bin/mbtileserver --port 8009 --dir /mnt/cattracks_volume/tdata/tilesets --enable-fs-watch --verbose

Dec 10 18:43:33 cattracks-debian-s-2vcpu-2gb-sfo3-01 systemd[1]: Started mbtileserver.service - mbtileserver.
Dec 10 18:43:33 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[701806]: time="2024-12-10T18:43:33Z" level=info msg="Searching for tilesets in /mnt/cattracks_volume/tdata/tilesets\n"
Dec 10 18:43:33 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[701806]: time="2024-12-10T18:43:33Z" level=info msg="Published 24 services"
Dec 10 18:43:33 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[701806]: time="2024-12-10T18:43:33Z" level=info msg="Watching /mnt/cattracks_volume/tdata/tilesets\n"
Dec 10 18:43:33 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[701806]: --------------------------------------
Dec 10 18:43:33 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[701806]: Use Ctrl-C to exit the server
Dec 10 18:43:33 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[701806]: --------------------------------------
Dec 10 18:43:33 cattracks-debian-s-2vcpu-2gb-sfo3-01 mbtileserver[701806]: HTTP server started on 0.0.0.0:8009
```
